utils::globalVariables(c(  "Run" , "R_FileName" ,
                            "Precursor.Id" , "PEP_GroupingKey" ,
                            "Modified.Sequence" , "FG_LabeledSequence" ,
                            "Stripped.Sequence" , "PEP_StrippedSequence" ,
                            "Precursor.Charge" , "FG_Charge" ,
                            "Protein.Group" , "PG_ProteinGroups",
                            "Genes" ,  "PG_ProteinNames",
                            "Protein.Names" , "PG_Genes",
                            "Precursor.Quantity", "FG_MS2RawQuantity"  ,
                            "Ms1.Area" , "FG_MS1RawQuantity",
                            "Lib.Q.Value" , "FG_Qvalue",
                           "AA_after","AA_last","AA_before","end",
                           "start","Protein.Sequence",
                           "total_repeats","precursor.Id", "adjPval", "logFC", "interest",
                           "repeat_nr","pep_type","CondRep","Pipeline",
                           "max_tier", "tier", "significance", "type",
                           "normPQ", "coverage", "median_abundance",".",
                           "pval", "completeness", "directionality",'tooltip_text',
                           "Proteotypic","value","deviation","df","se",
                          "Accession", "Tryptic","NonTryptic",'SemiTryptic','Condition','abundance_adjustment',
                          'log_Precursor.Quantity','sample_shared_median','sample_scaling_factor','Drug','ID'))

